// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByO0zvoxPuYS3Jc7jwkszmKWhSmWPXPDY',
    appId: '1:214816314000:web:9a50b340ba2d309c197e15',
    messagingSenderId: '214816314000',
    projectId: 'battle-boats-firebase',
    authDomain: 'battle-boats-firebase.firebaseapp.com',
    storageBucket: 'battle-boats-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfbQH-qbb7OOQKDwnTiQrPZTjo4e5AJA',
    appId: '1:214816314000:android:aadc62c0e3066dca197e15',
    messagingSenderId: '214816314000',
    projectId: 'battle-boats-firebase',
    storageBucket: 'battle-boats-firebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaY_gllC5GxIVuq5lQoihcdjGTuJ-3tFE',
    appId: '1:214816314000:ios:2b89fddf06a95b77197e15',
    messagingSenderId: '214816314000',
    projectId: 'battle-boats-firebase',
    storageBucket: 'battle-boats-firebase.firebasestorage.app',
    iosBundleId: 'com.example.battleBoats',
  );
}
